version: "3"
services:
  react:
    container_name: react_container
    build: .
    ports:
      - "80:80"
    networks:
      airquality_network:
        ipv4_address: 172.24.0.2

networks:
  airquality_network:
    ipam:
      config:
        - subnet: 172.24.0.0/24
